import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/Navbar";
import Popup from "../../components/Popup";

import Footer from "../../components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GoEdu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <link rel="icon" href="/goEdu 1.svg" />
      <body className={inter.className}>
        
         {/* <Navbar /> */}
         
      {/* <Popup /> */}
        {children}

        {/* <Footer /> */}
        
        </body>
    </html>
  );
}
