import { Inter } from "next/font/google";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "GoEdu",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <link rel="icon" href="/goEdu 1.svg" />
      <body className={inter.className}>
     
        {children}

        
        </body>
    </html>
  );
}
